apiVersion: v1
kind: Service
metadata:
  name: orc-service
spec:
  selector:
    app: orc-pod
  ports:
  - port: 8083
    nodePort: 30883
    protocol: TCP
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orc-pod
  template:
    metadata:
      labels:
        app: orc-pod
    spec:
      containers:
      - name: orc-container
        image: pichayean/orc-thai
        resources:
          limits:
            memory: "256Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: orc-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: orc.codingholiday.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: orc-service
           port:
             number: 80
